name: CloneRepo

on: 
  workflow_dispatch:
  push:

jobs:  
     job-public-repo-windows:
      runs-on: windows-latest
      steps:

        - name: rodalu/DemoClone PUBLIC repository
          uses: rodalu/DemoClone@main
          with:
              owner: 'rodalu'
              repository: 'DemoClone'
      
        - name: Access cloned repository content
          run: |
            echo "ROOT"
            ls -la
            echo "CLONED REPO"
            cd DemoClone
            ls -la
            shell: bash
            logLevel: debug
            checkForCommonlyIgnoredFiles:
              name: Check for commonly ignored files
              runs-on: ubuntu-latest
              steps:
                - name: Checkout repo
                  uses: actions/checkout@v2
          
                - name: Check if commit contains files that should be ignored
                  run: |
                    git clone --depth 1 https://github.com/rodalu/DemoClone/gitignore.git &&
                    cat gitignore/Node.gitignore $(find gitignore/Global -name "*.gitignore" | grep -v ModelSim) > all.gitignore &&
                    if  [[ "$(git ls-files -iX all.gitignore)" != "" ]]; then
                      echo "::error::Please remove these files:"
                      git ls-files -iX all.gitignore
                      exit 1
                    if