name: GraphQuery

on: 
    workflow_dispatch:
    push:

jobs: ## jobs to run when triggered
        echo-branch-name: ## name of a job
          runs-on: ubuntu-latest ## which machine the job runs on
          outputs:
            event_ref: '${{ github.event.ref }}'
         
          steps: ## steps to run
            - name: Step One ## name of a step
              run: | ## commands to run 
                #   echo '${{ github.event.ref }}'
          